attempt to address freezegun error in jenkins
> "/home/pusher/.jenkins/jobs/dmt/workspace/ve/local/lib/python2.7/site-packages/freezegun/api.py",
> line 193, in _time_to_freeze
>     return cls.times_to_freeze[-1]()
>     IndexError: list index out of range

I wasn't able to reproduce the problem at first, but after changing the
way I'm using freezegun in this test (manually starting and stopping it
in setUp and tearDown), I triggered the problem locally. Upgrading to
freezegun 0.3.6 fixed this problem for me, we'll see if it works on
jenkins.